project:
  type: website
  output-dir: docs
  # resources: 
  #   - qmds

website:
  title: "Data Cleaning Blog for My Regex Nerds"
  back-to-top-navigation: true
  repo-url: https://github.com/annakamc/DSS_Senior_project_Blog.github.io/tree/main

  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - text: Blog
        menu:
          - href: posts/welcome/index.html
            text: Welcome
          - href: posts/post-with-code/index.html
            text: Posts with Code
          - href: posts/real-life-examples/index.html
            text: Real World Use Cases
    right:
      - about.qmd
      - icon: github
        href: https://github.com/annakamc
      - icon: linkedin
        href: https://www.linkedin.com/in/annaka-mcc

format:
  html:
    theme: cosmo
    css: styles.css
